vyos:
  hosts:
    10.0.17.101:
      hostname: MGMT-FW
      lan_ip: 10.0.12.2   
      lan: 10.0.12.0/24
      dhcp_name_server: 10.0.12.5
      shared_network: Blue-MGMT
      dhcp_domain: mgmt.local
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: network_cli
    ansible_network_os: vyos
    ansible_user: vyos

