---
- name: domain joiner
  hosts: windows
  gather_facts: no
  vars_prompt:
  - name: user
    prompt: "provide a domain admin name ex: connor@blue2.local"
    private: no
  
  - name: pass
    prompt: "provide domain joiner account password"
    private: yes

  tasks:

  - name: Join Domain
    win_domain_membership:
      state: domain
      dns_domain_name: "{{ domain }}"
      hostname: "{{ hostname }}"
      domain_admin_user: "{{ user }}"
      domain_admin_password: "{{ pass }}"
      domain_ou_path: "{{ domain_ou_path }}"
    register: domain_state

  - name: Change DNS
    win_dns_client:
      adapter_names: "{{ device }}"
      ipv4_addresses:
      - "{{ name_server }}"

  - name: Reboot after creation
    when: domain_state.reboot_required
    win_reboot:
      msg: "Domain Join in progress; rebooting..."
      test_command: 'exit (Get-Service -Name WinRM).Status -ne "Running"'
